/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home_map`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/SplashDots`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/splash/splash_1`; params?: Router.UnknownInputParams; } | { pathname: `/splash/splash_2`; params?: Router.UnknownInputParams; } | { pathname: `/splash/splash_3`; params?: Router.UnknownInputParams; } | { pathname: `/tab/accueil`; params?: Router.UnknownInputParams; } | { pathname: `/tab/map`; params?: Router.UnknownInputParams; } | { pathname: `/tab/param`; params?: Router.UnknownInputParams; } | { pathname: `/tab/profil`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/home_map`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/SplashDots`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/splash/splash_1`; params?: Router.UnknownOutputParams; } | { pathname: `/splash/splash_2`; params?: Router.UnknownOutputParams; } | { pathname: `/splash/splash_3`; params?: Router.UnknownOutputParams; } | { pathname: `/tab/accueil`; params?: Router.UnknownOutputParams; } | { pathname: `/tab/map`; params?: Router.UnknownOutputParams; } | { pathname: `/tab/param`; params?: Router.UnknownOutputParams; } | { pathname: `/tab/profil`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/home_map${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/SplashDots${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/splash/splash_1${`?${string}` | `#${string}` | ''}` | `/splash/splash_2${`?${string}` | `#${string}` | ''}` | `/splash/splash_3${`?${string}` | `#${string}` | ''}` | `/tab/accueil${`?${string}` | `#${string}` | ''}` | `/tab/map${`?${string}` | `#${string}` | ''}` | `/tab/param${`?${string}` | `#${string}` | ''}` | `/tab/profil${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home_map`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/SplashDots`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/splash/splash_1`; params?: Router.UnknownInputParams; } | { pathname: `/splash/splash_2`; params?: Router.UnknownInputParams; } | { pathname: `/splash/splash_3`; params?: Router.UnknownInputParams; } | { pathname: `/tab/accueil`; params?: Router.UnknownInputParams; } | { pathname: `/tab/map`; params?: Router.UnknownInputParams; } | { pathname: `/tab/param`; params?: Router.UnknownInputParams; } | { pathname: `/tab/profil`; params?: Router.UnknownInputParams; };
    }
  }
}
